apiVersion: v2
name: stash-enterprise
description: Stash Enterprise Plan
type: application
version: v2020.6.23
appVersion: v2020.6.23
home: https://stash.run
icon: https://cdn.appscode.com/images/products/stash/icons/android-icon-192x192.png
sources:
- https://github.com/stashed
maintainers:
- name: appscode
  email: support@appscode.com
