apiVersion: v2
name: stash-community
description: Stash Community Plan
type: application
version: v2020.12.17
appVersion: v2020.12.17
home: https://stash.run
icon: https://cdn.appscode.com/images/products/stash/stash-community-icon.png
sources:
- https://github.com/stashed
maintainers:
- name: appscode
  email: support@appscode.com
