apiVersion: kubepack.com/v1alpha1
kind: Bundle
metadata:
  creationTimestamp: null
  name: '{{ include "stash-mongodb-community.fullname" . }}'
spec:
  description: stash-mongodb - MongoDB database plugin for Stash by AppsCode
  displayName: Stash MongoDB Bundle
  icons:
  - src: https://cdn.appscode.com/images/icon/stash.png
    type: image/png
  links:
  - description: website
    url: https://github.com/stashed/mongodb
  maintainers:
  - email: support@appscode.com
    name: appscode
  namespace: kube-system
  packages:
  - chart:
      features:
      - stash-mongodb - MongoDB database plugin for Stash by AppsCode
      multiSelect: true
      name: stash-mongodb
      required: true
      url: https://charts.appscode.com/stable/
      versions:
      - selected: true
        version: 4.2.3-beta.20200826
      - selected: true
        version: 4.1.7-beta.20200826
      - selected: true
        version: 4.1.4-beta.20200826
      - selected: true
        version: 4.1.1-beta.20200826
      - selected: true
        version: 4.0.5-beta.20200826
      - selected: true
        version: 4.0.3-beta.20200826
      - selected: true
        version: 4.0.1-beta.20200826
      - selected: true
        version: 3.6.8-beta.20200826
      - selected: true
        version: 3.6.1-beta.20200826
      - selected: true
        version: 3.4.2-beta.20200826
      - selected: true
        version: 3.4.1-beta.20200826
status: {}
