apiVersion: kubepack.com/v1alpha1
kind: Bundle
metadata:
  creationTimestamp: null
  name: '{{ include "stash-community.fullname" . }}'
spec:
  description: Stash by AppsCode - Backup your Kubernetes Volumes
  displayName: Stash Bundle
  icons:
  - src: https://cdn.appscode.com/images/products/stash/icons/android-icon-192x192.png
    type: image/png
  links:
  - description: website
    url: https://appscode.com/products/stash/
  maintainers:
  - email: support@appscode.com
    name: appscode
  namespace: kube-system
  packages:
  - chart:
      features:
      - Stash by AppsCode - Backup your Kubernetes Volumes
      name: stash-community
      required: true
      url: https://charts.appscode.com/stable
      versions:
      - version: v0.21.0
status: {}
